# Generated by Django 5.2.7 on 2025-11-26 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_product_sku_idx_product_product_name_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name', 'sku'], name='product_search_idx'),
        ),
    ]
