# Generated by Django 5.2.7 on 2025-11-26 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['name'], name='supplier_name_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['email'], name='supplier_email_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['cnpj'], name='supplier_cnpj_idx'),
        ),
    ]
